id: AE5E0F40B
title: Verses of Refuge and Bodhicitta
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:04:29.871726
  last_modified_at: 2022-03-01 03:04:29.871730
